name: CI

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  lint:
    name: Run static checker
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install -U poetry poethepoet
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Set up Python virtual environment
        run: poetry install
      - name: Run linter
        run: poe lint
      - name: Check types
        run: poe type-check
  test:
    name: Run test
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install -U poetry poethepoet
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Set up Python virtual environment
        run: poetry install
      - name: Run tests
        run: poe test --cov-report lcov:coverage/lcov.info
      - name: Coveralls
        if: ${{ matrix.python-version == '3.10' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pip install -U poetry poethepoet
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install Dependencies
        run: poetry install
      - name: Render docs
        run: poe docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
